<?php

namespace webservices\details;

require_once __DIR__ . '/../../config.php';
require_once __DIR__ . '/../../../db/cvterms.php';

/**
 * @backupGlobals disabled
 */
class IsoformTest extends \PHPUnit_Framework_TestCase
{
    public function testExecute()
    {
        list($service) = \WebService::factory('details/Isoform');
        
        $results = ($service->execute(array("query1"=>46)));
        $results = $results['isoform'];
        # This demo dataset contains no unigenes, we need another test database for better testing
        $this->assertEquals(46, $results['feature_id']);
        $this->assertEquals('gi|351629431|gb|JP482314.1|', $results['name']);
        $this->assertEquals('CGCAGAGGCCTAGTTACGGGGGAAAACAAAGAGAAGGATGGTCATGGTGGTAACAAGTGCAACGCATTCTTCACCATTTCTGACTTTCTCTTCACCTTCTTCTTCCCTATCTCGGCCCTCTCTCAGGTACGCAGTTCTGGGTGCTGGTTTTGCTGGTCTTTCTGTTGCCTGGCATTTGCTCCGAGAGAGTGCAAAGGACTTGAACATACGAATAGATATTTATGATGAAATTGGGATTGGGGGAGGTGCTTCTGGAATTTCTGGAGGACTAATTCATCCTTATTCCCCTAAAGCTAAGCTTCTATGGAAGGGTGCTGAGTGTTGGAATGAGTGTTTAAAGCTTTTGGGTGTTGCTGAAGCAGCAGAAGCATCAATGGATTCTGGCCAGTTAAACTCTGGAATTTCAGATTTTGATCCTAACCTTCAAGGCCTCATGGTTCGAAGAAGGGGAATCTTGAGGCCAGCAGTCAGCATGAAAAACATGCTATTGTTAAGCGATGTAATTATCTCTGAACTTGGTATGAGCACAAGGGCTTGGTGTTTGATTTTTGATGTTATTGTAATGTTGGTGCTTATTTCTCTGCGCCATTAGAATGCTCGGAGTTGTCTTTCCAGTTGCAGAATAGAAACTCTTGAGAAGGATGCTGTCCAAAATCTTGCACCCAATTTATGTTTACCCTTGAACAAGGCTTTCTACATGCCCGAGGCTGTAAATATCCATCCTCAACGTTATGTTCAGGCGCTTTACACGGCGTGTAAGAATTTAGCAAAAGAATTATCTGCATCTGGCGTTGGTGAAAAAGAGCTACACTTGCACAAGAAAAATGTTAACAAACTCACTGATTTAGAAGGGGAATACCAGGCAGTAATAATATGTCTAGGTGCCAAAGCAGACATGCTTCCTGAGCTTGCTGGAAGGATTCCTCTAAGGACATGTAGAGGTGTTGTTGCGCACCTGAAGCTGTCTGATGATATGGGAGAAGAGTATCCAGAGACTGGCCCTTCCATACTTTCAGATGCTTGGCTAGCTATCCAGGGGCCTCGAAGTTTGTACATGGGCTCTACATGGGAATGGAAATCAAGAAACTCTTCTCCAAATGTA', $results['residues']);
        $this->assertEquals(1102, $results['seqlen']);
        $this->assertEquals('2016-04-04 13:55:39.828445', $results['timeaccessioned']);
    }
}
?>