language: php
php:
  - '5.6'

install:
  - composer install

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - cp test/php/.travis.config.php test/php/config.php

after_success:
  - travis_retry php vendor/bin/coveralls -v
