<?php

namespace webservices\export;

require_once __DIR__ . '/../../config.php';
require_once __DIR__ . '/../../../db/cvterms.php';
require_once __DIR__ . DIRECTORY_SEPARATOR . 'overload_header_function.php';

/**
 * @backupGlobals disabled
 */
class PeptidesTest extends \PHPUnit_Framework_TestCase
{
    public function testExecute()
    {
        $expected_output = <<<EOF
>m.8152 REF=gi|351628743|gb|JP481626.1| START=3 END=557 STRAND=1
MVAQLPDKDETKISRKQMLARLDVCMGGRVAEELIFGENEVTSGASSDLEKATSIARAMVTQYGMSKEVGVVTHNYDDHGKSMSTETRLLIEKEVKSMLDTAYNNAKAILTAHFHELHALANALLEHETLTGSQINALLAKLNSKEQQQEQPQVISAKSSSQSNPVPPSAPNAAASAAAAAAAA
>m.10592 REF=gi|351628525|gb|JP481408.1| START=291 END=2642 STRAND=1
MTSSMLSGDRRWAPSTTGKRGGLTVLGKVVVPKPINLPSQRSENHGLDPNVEIVPKGTLGWGSKSSCPWGSSSLSPNTDGGGSPSFLSGRPSSGSGTRPSTASSDRAHEPTINVSGPNSRPSSASGALTSSQTSLIALRPRSAETRPGSSQLSRFAEHSEHQVAWNAAGTAEKLGVTPPKNDGFSLTSGDFPTLGSGKESSDQSSHSRPGSSSSGLGTTKERIGTSGTGDLSTRDIVKNDTVNSWKRDSPPYCEDGVRPGQEKWQGNNQTYPPHPQHYEFDGWRGAPLNNPQGGVWFRGPPGGPYGNPVAAAGYPMEPFPYYRPHMPTAGLPNPQPIPPPGAGPRGPHPKNGDMYRPHMPDAFIRPGVPMQPGFYPGPVTYEGYYGPPMGYCSSNDRDVPFMGMAARPVYNMYPGQVAPEPGNSHGRSSGYGSVNQTQVVEQVESVHPQDNRGPYKVLLKQHDGYDRKIEEHKSESAVALDTSRGDQPKTTSYWEDDWRSYKKDEVRDLRKAPVEEASFPNSDNKGALLVPVKVKSPSSGGNMKVIDEISGKKLESEALGLSKASPLPAAPKDSSLIQRLEELNAKARASDGRNETIIASSGEDRKNKFHSNAKGTQNRNESGGGSSYPEKTYTADISSSNNRKVGLSGGDKKLDSKVGSETNISRMSSQSSQSRSDHYGKGRFITQDGEGWQKKPSISESGAVNSETSNIHGHDHHRGSQEAENSGSGLLPHGKLEGQPLLPMLDRSNNQAQVNPLISTPLIINSFGILYIQLQNLIRRVST*

EOF;
        $this->expectOutputString($expected_output);
        list($service) = \WebService::factory('export/Peptides');
        $results = ($service->execute(array("terms"=>array(734,952))));

    }
}
