<?php

/**
 * This is the model base class for the table "control".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Control".
 *
 * Columns in table "control" available as properties of the model,
 * followed by relations of table "control" available as properties of the model.
 *
 * @property integer $control_id
 * @property integer $type_id
 * @property integer $assay_id
 * @property integer $tableinfo_id
 * @property integer $row_id
 * @property string $name
 * @property string $value
 * @property integer $rank
 *
 * @property Assay $assay
 * @property Tableinfo $tableinfo
 * @property Cvterm $type
 */
abstract class BaseControl extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'control';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Control|Controls', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('type_id, assay_id, tableinfo_id, row_id', 'required'),
			array('type_id, assay_id, tableinfo_id, row_id, rank', 'numerical', 'integerOnly'=>true),
			array('name, value', 'safe'),
			array('name, value, rank', 'default', 'setOnEmpty' => true, 'value' => null),
			array('control_id, type_id, assay_id, tableinfo_id, row_id, name, value, rank', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'assay' => array(self::BELONGS_TO, 'Assay', 'assay_id'),
			'tableinfo' => array(self::BELONGS_TO, 'Tableinfo', 'tableinfo_id'),
			'type' => array(self::BELONGS_TO, 'Cvterm', 'type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'control_id' => Yii::t('app', 'Control'),
			'type_id' => null,
			'assay_id' => null,
			'tableinfo_id' => null,
			'row_id' => Yii::t('app', 'Row'),
			'name' => Yii::t('app', 'Name'),
			'value' => Yii::t('app', 'Value'),
			'rank' => Yii::t('app', 'Rank'),
			'assay' => null,
			'tableinfo' => null,
			'type' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('control_id', $this->control_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('assay_id', $this->assay_id);
		$criteria->compare('tableinfo_id', $this->tableinfo_id);
		$criteria->compare('row_id', $this->row_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('rank', $this->rank);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}