<?php

/**
 * This is the model base class for the table "treatment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Treatment".
 *
 * Columns in table "treatment" available as properties of the model,
 * followed by relations of table "treatment" available as properties of the model.
 *
 * @property integer $treatment_id
 * @property integer $rank
 * @property integer $biomaterial_id
 * @property integer $type_id
 * @property integer $protocol_id
 * @property string $name
 *
 * @property Biomaterial $biomaterial
 * @property Protocol $protocol
 * @property Cvterm $type
 * @property BiomaterialTreatment[] $biomaterialTreatments
 */
abstract class BaseTreatment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'treatment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Treatment|Treatments', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('biomaterial_id, type_id', 'required'),
			array('rank, biomaterial_id, type_id, protocol_id', 'numerical', 'integerOnly'=>true),
			array('name', 'safe'),
			array('rank, protocol_id, name', 'default', 'setOnEmpty' => true, 'value' => null),
			array('treatment_id, rank, biomaterial_id, type_id, protocol_id, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'biomaterial' => array(self::BELONGS_TO, 'Biomaterial', 'biomaterial_id'),
			'protocol' => array(self::BELONGS_TO, 'Protocol', 'protocol_id'),
			'type' => array(self::BELONGS_TO, 'Cvterm', 'type_id'),
			'biomaterialTreatments' => array(self::HAS_MANY, 'BiomaterialTreatment', 'treatment_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'treatment_id' => Yii::t('app', 'Treatment'),
			'rank' => Yii::t('app', 'Rank'),
			'biomaterial_id' => null,
			'type_id' => null,
			'protocol_id' => null,
			'name' => Yii::t('app', 'Name'),
			'biomaterial' => null,
			'protocol' => null,
			'type' => null,
			'biomaterialTreatments' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('treatment_id', $this->treatment_id);
		$criteria->compare('rank', $this->rank);
		$criteria->compare('biomaterial_id', $this->biomaterial_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('protocol_id', $this->protocol_id);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}