<?php

/**
 * This is the model base class for the table "assayprop".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Assayprop".
 *
 * Columns in table "assayprop" available as properties of the model,
 * followed by relations of table "assayprop" available as properties of the model.
 *
 * @property integer $assayprop_id
 * @property integer $assay_id
 * @property integer $type_id
 * @property string $value
 * @property integer $rank
 *
 * @property Assay $assay
 * @property Cvterm $type
 */
abstract class BaseAssayprop extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'assayprop';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Assayprop|Assayprops', $n);
	}

	public static function representingColumn() {
		return 'value';
	}

	public function rules() {
		return array(
			array('assay_id, type_id', 'required'),
			array('assay_id, type_id, rank', 'numerical', 'integerOnly'=>true),
			array('value', 'safe'),
			array('value, rank', 'default', 'setOnEmpty' => true, 'value' => null),
			array('assayprop_id, assay_id, type_id, value, rank', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'assay' => array(self::BELONGS_TO, 'Assay', 'assay_id'),
			'type' => array(self::BELONGS_TO, 'Cvterm', 'type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'assayprop_id' => Yii::t('app', 'Assayprop'),
			'assay_id' => null,
			'type_id' => null,
			'value' => Yii::t('app', 'Value'),
			'rank' => Yii::t('app', 'Rank'),
			'assay' => null,
			'type' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('assayprop_id', $this->assayprop_id);
		$criteria->compare('assay_id', $this->assay_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('rank', $this->rank);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}