<?php

/**
 * This is the model base class for the table "analysisprop".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Analysisprop".
 *
 * Columns in table "analysisprop" available as properties of the model,
 * followed by relations of table "analysisprop" available as properties of the model.
 *
 * @property integer $analysisprop_id
 * @property integer $analysis_id
 * @property integer $type_id
 * @property string $value
 * @property integer $rank
 *
 * @property Analysis $analysis
 * @property Cvterm $type
 */
abstract class BaseAnalysisprop extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'analysisprop';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Analysisprop|Analysisprops', $n);
	}

	public static function representingColumn() {
		return 'value';
	}

	public function rules() {
		return array(
			array('analysis_id, type_id', 'required'),
			array('analysis_id, type_id, rank', 'numerical', 'integerOnly'=>true),
			array('value', 'safe'),
			array('value, rank', 'default', 'setOnEmpty' => true, 'value' => null),
			array('analysisprop_id, analysis_id, type_id, value, rank', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'analysis' => array(self::BELONGS_TO, 'Analysis', 'analysis_id'),
			'type' => array(self::BELONGS_TO, 'Cvterm', 'type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'analysisprop_id' => Yii::t('app', 'Analysisprop'),
			'analysis_id' => null,
			'type_id' => null,
			'value' => Yii::t('app', 'Value'),
			'rank' => Yii::t('app', 'Rank'),
			'analysis' => null,
			'type' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('analysisprop_id', $this->analysisprop_id);
		$criteria->compare('analysis_id', $this->analysis_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('rank', $this->rank);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}