<?php

/**
 * This is the model base class for the table "channel".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Channel".
 *
 * Columns in table "channel" available as properties of the model,
 * followed by relations of table "channel" available as properties of the model.
 *
 * @property integer $channel_id
 * @property string $name
 * @property string $definition
 *
 * @property Acquisition[] $acquisitions
 * @property AssayBiomaterial[] $assayBiomaterials
 */
abstract class BaseChannel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'channel';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Channel|Channels', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, definition', 'required'),
			array('channel_id, name, definition', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'acquisitions' => array(self::HAS_MANY, 'Acquisition', 'channel_id'),
			'assayBiomaterials' => array(self::HAS_MANY, 'AssayBiomaterial', 'channel_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'channel_id' => Yii::t('app', 'Channel'),
			'name' => Yii::t('app', 'Name'),
			'definition' => Yii::t('app', 'Definition'),
			'acquisitions' => null,
			'assayBiomaterials' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('channel_id', $this->channel_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('definition', $this->definition, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}