<?php

/**
 * This is the model base class for the table "assay_project".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AssayProject".
 *
 * Columns in table "assay_project" available as properties of the model,
 * followed by relations of table "assay_project" available as properties of the model.
 *
 * @property integer $assay_project_id
 * @property integer $assay_id
 * @property integer $project_id
 *
 * @property Assay $assay
 * @property Project $project
 */
abstract class BaseAssayProject extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'assay_project';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AssayProject|AssayProjects', $n);
	}

	public static function representingColumn() {
		return 'assay_project_id';
	}

	public function rules() {
		return array(
			array('assay_id, project_id', 'required'),
			array('assay_id, project_id', 'numerical', 'integerOnly'=>true),
			array('assay_project_id, assay_id, project_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'assay' => array(self::BELONGS_TO, 'Assay', 'assay_id'),
			'project' => array(self::BELONGS_TO, 'Project', 'project_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'assay_project_id' => Yii::t('app', 'Assay Project'),
			'assay_id' => null,
			'project_id' => null,
			'assay' => null,
			'project' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('assay_project_id', $this->assay_project_id);
		$criteria->compare('assay_id', $this->assay_id);
		$criteria->compare('project_id', $this->project_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}