<?php

/**
 * This is the model base class for the table "acquisition_relationship".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AcquisitionRelationship".
 *
 * Columns in table "acquisition_relationship" available as properties of the model,
 * followed by relations of table "acquisition_relationship" available as properties of the model.
 *
 * @property integer $acquisition_relationship_id
 * @property integer $subject_id
 * @property integer $type_id
 * @property integer $object_id
 * @property string $value
 * @property integer $rank
 *
 * @property Acquisition $object
 * @property Acquisition $subject
 * @property Cvterm $type
 */
abstract class BaseAcquisitionRelationship extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'acquisition_relationship';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AcquisitionRelationship|AcquisitionRelationships', $n);
	}

	public static function representingColumn() {
		return 'value';
	}

	public function rules() {
		return array(
			array('subject_id, type_id, object_id', 'required'),
			array('subject_id, type_id, object_id, rank', 'numerical', 'integerOnly'=>true),
			array('value', 'safe'),
			array('value, rank', 'default', 'setOnEmpty' => true, 'value' => null),
			array('acquisition_relationship_id, subject_id, type_id, object_id, value, rank', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'object' => array(self::BELONGS_TO, 'Acquisition', 'object_id'),
			'subject' => array(self::BELONGS_TO, 'Acquisition', 'subject_id'),
			'type' => array(self::BELONGS_TO, 'Cvterm', 'type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'acquisition_relationship_id' => Yii::t('app', 'Acquisition Relationship'),
			'subject_id' => null,
			'type_id' => null,
			'object_id' => null,
			'value' => Yii::t('app', 'Value'),
			'rank' => Yii::t('app', 'Rank'),
			'object' => null,
			'subject' => null,
			'type' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('acquisition_relationship_id', $this->acquisition_relationship_id);
		$criteria->compare('subject_id', $this->subject_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('object_id', $this->object_id);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('rank', $this->rank);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}