<?php

/**
 * This is the model base class for the table "biomaterial_relationship".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BiomaterialRelationship".
 *
 * Columns in table "biomaterial_relationship" available as properties of the model,
 * followed by relations of table "biomaterial_relationship" available as properties of the model.
 *
 * @property integer $biomaterial_relationship_id
 * @property integer $subject_id
 * @property integer $type_id
 * @property integer $object_id
 *
 * @property Biomaterial $object
 * @property Biomaterial $subject
 * @property Cvterm $type
 */
abstract class BaseBiomaterialRelationship extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'biomaterial_relationship';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BiomaterialRelationship|BiomaterialRelationships', $n);
	}

	public static function representingColumn() {
		return 'biomaterial_relationship_id';
	}

	public function rules() {
		return array(
			array('subject_id, type_id, object_id', 'required'),
			array('subject_id, type_id, object_id', 'numerical', 'integerOnly'=>true),
			array('biomaterial_relationship_id, subject_id, type_id, object_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'object' => array(self::BELONGS_TO, 'Biomaterial', 'object_id'),
			'subject' => array(self::BELONGS_TO, 'Biomaterial', 'subject_id'),
			'type' => array(self::BELONGS_TO, 'Cvterm', 'type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'biomaterial_relationship_id' => Yii::t('app', 'Biomaterial Relationship'),
			'subject_id' => null,
			'type_id' => null,
			'object_id' => null,
			'object' => null,
			'subject' => null,
			'type' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('biomaterial_relationship_id', $this->biomaterial_relationship_id);
		$criteria->compare('subject_id', $this->subject_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('object_id', $this->object_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}