<?php

/**
 * This is the model base class for the table "elementresult".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Elementresult".
 *
 * Columns in table "elementresult" available as properties of the model,
 * followed by relations of table "elementresult" available as properties of the model.
 *
 * @property integer $elementresult_id
 * @property integer $element_id
 * @property integer $quantification_id
 * @property double $signal
 *
 * @property ElementresultRelationship[] $elementresultRelationships
 * @property ElementresultRelationship[] $elementresultRelationships1
 * @property Element $element
 * @property Quantification $quantification
 */
abstract class BaseElementresult extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'elementresult';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Elementresult|Elementresults', $n);
	}

	public static function representingColumn() {
		return 'elementresult_id';
	}

	public function rules() {
		return array(
			array('element_id, quantification_id, signal', 'required'),
			array('element_id, quantification_id', 'numerical', 'integerOnly'=>true),
			array('signal', 'numerical'),
			array('elementresult_id, element_id, quantification_id, signal', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'elementresultRelationships' => array(self::HAS_MANY, 'ElementresultRelationship', 'object_id'),
			'elementresultRelationships1' => array(self::HAS_MANY, 'ElementresultRelationship', 'subject_id'),
			'element' => array(self::BELONGS_TO, 'Element', 'element_id'),
			'quantification' => array(self::BELONGS_TO, 'Quantification', 'quantification_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'elementresult_id' => Yii::t('app', 'Elementresult'),
			'element_id' => null,
			'quantification_id' => null,
			'signal' => Yii::t('app', 'Signal'),
			'elementresultRelationships' => null,
			'elementresultRelationships1' => null,
			'element' => null,
			'quantification' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('elementresult_id', $this->elementresult_id);
		$criteria->compare('element_id', $this->element_id);
		$criteria->compare('quantification_id', $this->quantification_id);
		$criteria->compare('signal', $this->signal);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}