<?php

/**
 * This is the model base class for the table "biomaterial_treatment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BiomaterialTreatment".
 *
 * Columns in table "biomaterial_treatment" available as properties of the model,
 * followed by relations of table "biomaterial_treatment" available as properties of the model.
 *
 * @property integer $biomaterial_treatment_id
 * @property integer $biomaterial_id
 * @property integer $treatment_id
 * @property integer $unittype_id
 * @property double $value
 * @property integer $rank
 *
 * @property Biomaterial $biomaterial
 * @property Treatment $treatment
 * @property Cvterm $unittype
 */
abstract class BaseBiomaterialTreatment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'biomaterial_treatment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BiomaterialTreatment|BiomaterialTreatments', $n);
	}

	public static function representingColumn() {
		return 'biomaterial_treatment_id';
	}

	public function rules() {
		return array(
			array('biomaterial_id, treatment_id', 'required'),
			array('biomaterial_id, treatment_id, unittype_id, rank', 'numerical', 'integerOnly'=>true),
			array('value', 'numerical'),
			array('unittype_id, value, rank', 'default', 'setOnEmpty' => true, 'value' => null),
			array('biomaterial_treatment_id, biomaterial_id, treatment_id, unittype_id, value, rank', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'biomaterial' => array(self::BELONGS_TO, 'Biomaterial', 'biomaterial_id'),
			'treatment' => array(self::BELONGS_TO, 'Treatment', 'treatment_id'),
			'unittype' => array(self::BELONGS_TO, 'Cvterm', 'unittype_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'biomaterial_treatment_id' => Yii::t('app', 'Biomaterial Treatment'),
			'biomaterial_id' => null,
			'treatment_id' => null,
			'unittype_id' => null,
			'value' => Yii::t('app', 'Value'),
			'rank' => Yii::t('app', 'Rank'),
			'biomaterial' => null,
			'treatment' => null,
			'unittype' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('biomaterial_treatment_id', $this->biomaterial_treatment_id);
		$criteria->compare('biomaterial_id', $this->biomaterial_id);
		$criteria->compare('treatment_id', $this->treatment_id);
		$criteria->compare('unittype_id', $this->unittype_id);
		$criteria->compare('value', $this->value);
		$criteria->compare('rank', $this->rank);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}