<?php

/**
 * This is the model base class for the table "quantificationprop".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Quantificationprop".
 *
 * Columns in table "quantificationprop" available as properties of the model,
 * followed by relations of table "quantificationprop" available as properties of the model.
 *
 * @property integer $quantificationprop_id
 * @property integer $quantification_id
 * @property integer $type_id
 * @property string $value
 * @property integer $rank
 *
 * @property Quantification $quantification
 * @property Cvterm $type
 */
abstract class BaseQuantificationprop extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'quantificationprop';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Quantificationprop|Quantificationprops', $n);
	}

	public static function representingColumn() {
		return 'value';
	}

	public function rules() {
		return array(
			array('quantification_id, type_id', 'required'),
			array('quantification_id, type_id, rank', 'numerical', 'integerOnly'=>true),
			array('value', 'safe'),
			array('value, rank', 'default', 'setOnEmpty' => true, 'value' => null),
			array('quantificationprop_id, quantification_id, type_id, value, rank', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'quantification' => array(self::BELONGS_TO, 'Quantification', 'quantification_id'),
			'type' => array(self::BELONGS_TO, 'Cvterm', 'type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'quantificationprop_id' => Yii::t('app', 'Quantificationprop'),
			'quantification_id' => null,
			'type_id' => null,
			'value' => Yii::t('app', 'Value'),
			'rank' => Yii::t('app', 'Rank'),
			'quantification' => null,
			'type' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('quantificationprop_id', $this->quantificationprop_id);
		$criteria->compare('quantification_id', $this->quantification_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('rank', $this->rank);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}