<?php

/**
 * This is the model base class for the table "biomaterialprop".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Biomaterialprop".
 *
 * Columns in table "biomaterialprop" available as properties of the model,
 * followed by relations of table "biomaterialprop" available as properties of the model.
 *
 * @property integer $biomaterialprop_id
 * @property integer $biomaterial_id
 * @property integer $type_id
 * @property string $value
 * @property integer $rank
 *
 * @property Biomaterial $biomaterial
 * @property Cvterm $type
 */
abstract class BaseBiomaterialprop extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'biomaterialprop';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Biomaterialprop|Biomaterialprops', $n);
	}

	public static function representingColumn() {
		return 'value';
	}

	public function rules() {
		return array(
			array('biomaterial_id, type_id', 'required'),
			array('biomaterial_id, type_id, rank', 'numerical', 'integerOnly'=>true),
			array('value', 'safe'),
			array('value, rank', 'default', 'setOnEmpty' => true, 'value' => null),
			array('biomaterialprop_id, biomaterial_id, type_id, value, rank', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'biomaterial' => array(self::BELONGS_TO, 'Biomaterial', 'biomaterial_id'),
			'type' => array(self::BELONGS_TO, 'Cvterm', 'type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'biomaterialprop_id' => Yii::t('app', 'Biomaterialprop'),
			'biomaterial_id' => null,
			'type_id' => null,
			'value' => Yii::t('app', 'Value'),
			'rank' => Yii::t('app', 'Rank'),
			'biomaterial' => null,
			'type' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('biomaterialprop_id', $this->biomaterialprop_id);
		$criteria->compare('biomaterial_id', $this->biomaterial_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('rank', $this->rank);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}