<?php

/**
 * This is the model base class for the table "acquisitionprop".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Acquisitionprop".
 *
 * Columns in table "acquisitionprop" available as properties of the model,
 * followed by relations of table "acquisitionprop" available as properties of the model.
 *
 * @property integer $acquisitionprop_id
 * @property integer $acquisition_id
 * @property integer $type_id
 * @property string $value
 * @property integer $rank
 *
 * @property Acquisition $acquisition
 * @property Cvterm $type
 */
abstract class BaseAcquisitionprop extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'acquisitionprop';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Acquisitionprop|Acquisitionprops', $n);
	}

	public static function representingColumn() {
		return 'value';
	}

	public function rules() {
		return array(
			array('acquisition_id, type_id', 'required'),
			array('acquisition_id, type_id, rank', 'numerical', 'integerOnly'=>true),
			array('value', 'safe'),
			array('value, rank', 'default', 'setOnEmpty' => true, 'value' => null),
			array('acquisitionprop_id, acquisition_id, type_id, value, rank', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'acquisition' => array(self::BELONGS_TO, 'Acquisition', 'acquisition_id'),
			'type' => array(self::BELONGS_TO, 'Cvterm', 'type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'acquisitionprop_id' => Yii::t('app', 'Acquisitionprop'),
			'acquisition_id' => null,
			'type_id' => null,
			'value' => Yii::t('app', 'Value'),
			'rank' => Yii::t('app', 'Rank'),
			'acquisition' => null,
			'type' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('acquisitionprop_id', $this->acquisitionprop_id);
		$criteria->compare('acquisition_id', $this->acquisition_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('rank', $this->rank);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}