<?php

/**
 * This is the model base class for the table "study_assay".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StudyAssay".
 *
 * Columns in table "study_assay" available as properties of the model,
 * followed by relations of table "study_assay" available as properties of the model.
 *
 * @property integer $study_assay_id
 * @property integer $study_id
 * @property integer $assay_id
 *
 * @property Assay $assay
 * @property Study $study
 */
abstract class BaseStudyAssay extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'study_assay';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'StudyAssay|StudyAssays', $n);
	}

	public static function representingColumn() {
		return 'study_assay_id';
	}

	public function rules() {
		return array(
			array('study_id, assay_id', 'required'),
			array('study_id, assay_id', 'numerical', 'integerOnly'=>true),
			array('study_assay_id, study_id, assay_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'assay' => array(self::BELONGS_TO, 'Assay', 'assay_id'),
			'study' => array(self::BELONGS_TO, 'Study', 'study_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'study_assay_id' => Yii::t('app', 'Study Assay'),
			'study_id' => null,
			'assay_id' => null,
			'assay' => null,
			'study' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('study_assay_id', $this->study_assay_id);
		$criteria->compare('study_id', $this->study_id);
		$criteria->compare('assay_id', $this->assay_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}