<?php

/**
 * This is the model base class for the table "project_contact".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProjectContact".
 *
 * Columns in table "project_contact" available as properties of the model,
 * followed by relations of table "project_contact" available as properties of the model.
 *
 * @property integer $project_contact_id
 * @property integer $project_id
 * @property integer $contact_id
 *
 * @property Contact $contact
 * @property Project $project
 */
abstract class BaseProjectContact extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'project_contact';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProjectContact|ProjectContacts', $n);
	}

	public static function representingColumn() {
		return 'project_contact_id';
	}

	public function rules() {
		return array(
			array('project_id, contact_id', 'required'),
			array('project_id, contact_id', 'numerical', 'integerOnly'=>true),
			array('project_contact_id, project_id, contact_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'contact' => array(self::BELONGS_TO, 'Contact', 'contact_id'),
			'project' => array(self::BELONGS_TO, 'Project', 'project_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'project_contact_id' => Yii::t('app', 'Project Contact'),
			'project_id' => null,
			'contact_id' => null,
			'contact' => null,
			'project' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('project_contact_id', $this->project_contact_id);
		$criteria->compare('project_id', $this->project_id);
		$criteria->compare('contact_id', $this->contact_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}