<?php

/**
 * This is the model base class for the table "contact_relationship".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ContactRelationship".
 *
 * Columns in table "contact_relationship" available as properties of the model,
 * followed by relations of table "contact_relationship" available as properties of the model.
 *
 * @property integer $contact_relationship_id
 * @property integer $type_id
 * @property integer $subject_id
 * @property integer $object_id
 *
 * @property Contact $object
 * @property Contact $subject
 * @property Cvterm $type
 */
abstract class BaseContactRelationship extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'contact_relationship';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ContactRelationship|ContactRelationships', $n);
	}

	public static function representingColumn() {
		return 'contact_relationship_id';
	}

	public function rules() {
		return array(
			array('type_id, subject_id, object_id', 'required'),
			array('type_id, subject_id, object_id', 'numerical', 'integerOnly'=>true),
			array('contact_relationship_id, type_id, subject_id, object_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'object' => array(self::BELONGS_TO, 'Contact', 'object_id'),
			'subject' => array(self::BELONGS_TO, 'Contact', 'subject_id'),
			'type' => array(self::BELONGS_TO, 'Cvterm', 'type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'contact_relationship_id' => Yii::t('app', 'Contact Relationship'),
			'type_id' => null,
			'subject_id' => null,
			'object_id' => null,
			'object' => null,
			'subject' => null,
			'type' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('contact_relationship_id', $this->contact_relationship_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('subject_id', $this->subject_id);
		$criteria->compare('object_id', $this->object_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}