<?php

/**
 * This is the model base class for the table "biomaterial".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Biomaterial".
 *
 * Columns in table "biomaterial" available as properties of the model,
 * followed by relations of table "biomaterial" available as properties of the model.
 *
 * @property integer $biomaterial_id
 * @property integer $taxon_id
 * @property integer $biosourceprovider_id
 * @property integer $dbxref_id
 * @property string $name
 * @property string $description
 *
 * @property Biomaterialprop[] $biomaterialprops
 * @property Treatment[] $treatments
 * @property Quantificationresult[] $quantificationresults
 * @property BiomaterialTreatment[] $biomaterialTreatments
 * @property Contact $biosourceprovider
 * @property Dbxref $dbxref
 * @property Organism $taxon
 * @property BiomaterialRelationship[] $biomaterialRelationships
 * @property BiomaterialRelationship[] $biomaterialRelationships1
 * @property BiomaterialDbxref[] $biomaterialDbxrefs
 * @property AssayBiomaterial[] $assayBiomaterials
 */
abstract class BaseBiomaterial extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'biomaterial';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Biomaterial|Biomaterials', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('taxon_id, biosourceprovider_id, dbxref_id', 'numerical', 'integerOnly'=>true),
			array('name, description', 'safe'),
			array('taxon_id, biosourceprovider_id, dbxref_id, name, description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('biomaterial_id, taxon_id, biosourceprovider_id, dbxref_id, name, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'biomaterialprops' => array(self::HAS_MANY, 'Biomaterialprop', 'biomaterial_id'),
			'treatments' => array(self::HAS_MANY, 'Treatment', 'biomaterial_id'),
			'quantificationresults' => array(self::HAS_MANY, 'Quantificationresult', 'biomaterial_id'),
			'biomaterialTreatments' => array(self::HAS_MANY, 'BiomaterialTreatment', 'biomaterial_id'),
			'biosourceprovider' => array(self::BELONGS_TO, 'Contact', 'biosourceprovider_id'),
			'dbxref' => array(self::BELONGS_TO, 'Dbxref', 'dbxref_id'),
			'taxon' => array(self::BELONGS_TO, 'Organism', 'taxon_id'),
			'biomaterialRelationships' => array(self::HAS_MANY, 'BiomaterialRelationship', 'object_id'),
			'biomaterialRelationships1' => array(self::HAS_MANY, 'BiomaterialRelationship', 'subject_id'),
			'biomaterialDbxrefs' => array(self::HAS_MANY, 'BiomaterialDbxref', 'biomaterial_id'),
			'assayBiomaterials' => array(self::HAS_MANY, 'AssayBiomaterial', 'biomaterial_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'biomaterial_id' => Yii::t('app', 'Biomaterial'),
			'taxon_id' => null,
			'biosourceprovider_id' => null,
			'dbxref_id' => null,
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'biomaterialprops' => null,
			'treatments' => null,
			'quantificationresults' => null,
			'biomaterialTreatments' => null,
			'biosourceprovider' => null,
			'dbxref' => null,
			'taxon' => null,
			'biomaterialRelationships' => null,
			'biomaterialRelationships1' => null,
			'biomaterialDbxrefs' => null,
			'assayBiomaterials' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('biomaterial_id', $this->biomaterial_id);
		$criteria->compare('taxon_id', $this->taxon_id);
		$criteria->compare('biosourceprovider_id', $this->biosourceprovider_id);
		$criteria->compare('dbxref_id', $this->dbxref_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}