<?php
// This file generated by Propel 1.6.8 convert-conf target
$conf = array (
  'datasources' => 
  array (
    'cli_db' => 
    array (
      'adapter' => DB_ADAPTER,
      'connection' => 
      array (
        'dsn' => DB_CONNSTR,
        'user' => DB_USERNAME,
        'password' => DB_PASSWORD,
      ),
    ),
    'default' => 'cli_db',
  ),
  'generator_version' => '1.6.8',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-cli_db-conf.php');
return $conf;
